
package service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PriceServiceImplService", targetNamespace = "http://service/", wsdlLocation = "http://localhost:8090/price_service/prices?wsdl")
public class PriceServiceImplService
    extends Service
{

    private final static URL PRICESERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException PRICESERVICEIMPLSERVICE_EXCEPTION;
    private final static QName PRICESERVICEIMPLSERVICE_QNAME = new QName("http://service/", "PriceServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8090/price_service/prices?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PRICESERVICEIMPLSERVICE_WSDL_LOCATION = url;
        PRICESERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public PriceServiceImplService() {
        super(__getWsdlLocation(), PRICESERVICEIMPLSERVICE_QNAME);
    }

    public PriceServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PRICESERVICEIMPLSERVICE_QNAME, features);
    }

    public PriceServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, PRICESERVICEIMPLSERVICE_QNAME);
    }

    public PriceServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRICESERVICEIMPLSERVICE_QNAME, features);
    }

    public PriceServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PriceServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PriceService
     */
    @WebEndpoint(name = "PriceServiceImplPort")
    public PriceService getPriceServiceImplPort() {
        return super.getPort(new QName("http://service/", "PriceServiceImplPort"), PriceService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PriceService
     */
    @WebEndpoint(name = "PriceServiceImplPort")
    public PriceService getPriceServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service/", "PriceServiceImplPort"), PriceService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PRICESERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw PRICESERVICEIMPLSERVICE_EXCEPTION;
        }
        return PRICESERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
